apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appdemo-secret
  name: appdemo-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdemo-secret
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appdemo-secret
    spec:
      containers:
      - image: eroilab.azurecr.io/header:v2
        name: header
        resources: {}
      imagePullSecrets:
      - name: myacrlogin
status: {}
